export const LOT_LIST_REQUEST = 'LOT_LIST_REQUEST'
export const LOT_LIST_SUCCESS = 'LOT_LIST_SUCCESS'
export const LOT_LIST_FAIL = 'LOT_LIST_FAIL'


export const LOT_DETAILS_REQUEST = 'LOT_DETAILS_REQUEST'
export const LOT_DETAILS_SUCCESS = 'LOT_DETAILS_SUCCESS'
export const LOT_DETAILS_FAIL = 'LOT_DETAILS_FAIL'


export const LOT_DELETE_REQUEST = 'LOT_DELETE_REQUEST'
export const LOT_DELETE_SUCCESS = 'LOT_DELETE_SUCCESS'
export const LOT_DELETE_FAIL = 'LOT_DELETE_FAIL'

export const LOT_CREATE_REQUEST = 'LOT_CREATE_REQUEST'
export const LOT_CREATE_SUCCESS = 'LOT_CREATE_SUCCESS'
export const LOT_CREATE_FAIL = 'LOT_CREATE_FAIL'
export const LOT_CREATE_RESET = 'LOT_CREATE_RESET'


export const LOT_UPDATE_REQUEST = 'LOT_UPDATE_REQUEST'
export const LOT_UPDATE_SUCCESS = 'LOT_UPDATE_SUCCESS'
export const LOT_UPDATE_FAIL = 'LOT_UPDATE_FAIL'
export const LOT_UPDATE_RESET = 'LOT_UPDATE_RESET'
